# Generated by Django 4.1.1 on 2022-09-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=8)),
                ('phone', models.IntegerField(max_length=12)),
                ('name', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=False)),
                ('fk_room_code', models.CharField(max_length=8)),
                ('fk_customer_code', models.CharField(max_length=8)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('capacity', models.IntegerField(max_length=7)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
