# Generated by Django 4.1.1 on 2022-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_customers_events_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
